/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Bill {
  'id' : bigint,
  'totalGST' : bigint,
  'grandTotal' : bigint,
  'billDate' : Time,
  'billNumber' : bigint,
  'paymentMode' : PaymentMode,
  'customerId' : bigint,
  'items' : Array<BillItem>,
  'totalDiscount' : bigint,
  'subtotal' : bigint,
}
export interface BillItem {
  'discountPercent' : bigint,
  'gstAmount' : bigint,
  'quantity' : bigint,
  'unitPrice' : bigint,
  'medicineId' : bigint,
}
export interface Customer {
  'id' : bigint,
  'name' : string,
  'email' : string,
  'address' : string,
  'phone' : string,
}
export interface DashboardStats {
  'todayBillCount' : bigint,
  'lowStockMedicinesCount' : bigint,
  'todayTotalSales' : bigint,
  'totalMedicinesInStock' : bigint,
}
export interface Medicine {
  'id' : bigint,
  'manufacturer' : string,
  'purchasePrice' : bigint,
  'expiryDate' : string,
  'name' : string,
  'unit' : Unit,
  'gstPercent' : bigint,
  'sellingPrice' : bigint,
  'rackLocation' : string,
  'hsnCode' : string,
  'batchNumber' : string,
  'genericName' : string,
  'reorderLevel' : bigint,
  'currentStock' : bigint,
}
export type PaymentMode = { 'UPI' : null } |
  { 'card' : null } |
  { 'cash' : null };
export type Time = bigint;
export type Unit = { 'bottle' : null } |
  { 'tablet' : null } |
  { 'strip' : null };
export interface UserProfile { 'name' : string, 'role' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addCustomer' : ActorMethod<[Customer], bigint>,
  'addMedicine' : ActorMethod<[Medicine], bigint>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createBill' : ActorMethod<[Bill], bigint>,
  'deleteCustomer' : ActorMethod<[bigint], undefined>,
  'deleteMedicine' : ActorMethod<[bigint], undefined>,
  'getAllBills' : ActorMethod<[], Array<Bill>>,
  'getAllCustomers' : ActorMethod<[], Array<Customer>>,
  'getAllMedicines' : ActorMethod<[], Array<Medicine>>,
  'getBill' : ActorMethod<[bigint], Bill>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCustomer' : ActorMethod<[bigint], Customer>,
  'getDashboardStats' : ActorMethod<[], DashboardStats>,
  'getMedicine' : ActorMethod<[bigint], Medicine>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'initialize' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateCustomer' : ActorMethod<[Customer], undefined>,
  'updateMedicine' : ActorMethod<[Medicine], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];